name: 2020
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/2020.yaml'
      - 'lang/**'
      - 'lib/**'
      - '2020/**/test.sh'
      - '2020/**/io/**'
      - '2020/**/solutions/**'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/2020.yaml'
      - 'lang/**'
      - 'lib/**'
      - '2020/**/test.sh'
      - '2020/**/io/**'
      - '2020/**/solutions/**'

jobs:
  fetch_latest_container:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.lowercase_repo.outputs.image_name }}
    steps:
      - id: lowercase_repo
        run: echo "::set-output name=image_name::${GITHUB_REPOSITORY,,}"
  days:
    needs: fetch_latest_container
    runs-on: ubuntu-latest
    container: ghcr.io/${{ needs.fetch_latest_container.outputs.image }}:latest
    strategy:
      matrix:
        day: [day01, day02, day03, day04, day05, day06, day07, day08, day09, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22, day23, day24, day25]
    steps:
      - name: Run ${{ matrix.day }}
      - uses: ./.github/actions/run_day
        with:
          year: 2020
          day: ${{ matrix.day }}
