name: 2021
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/2021.yaml'
      - 'lang/**'
      - 'lib/**'
      - '2021/**/test.sh'
      - '2021/**/io/**'
      - '2021/**/solutions/**'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/2021.yaml'
      - 'lang/**'
      - 'lib/**'
      - '2021/**/test.sh'
      - '2021/**/io/**'
      - '2021/**/solutions/**'

jobs:
  get_latest_image_and_solutions:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.lowercase_repo.outputs.image_name }}
      matrix: ${{ steps.get_days.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: lowercase_repo
        run: echo "::set-output name=image_name::${GITHUB_REPOSITORY,,}"
      - id: get_days
        run: |
          JSON=$(./scripts/days-with-solutions.sh 2021)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

  days:
    needs: get_latest_image_and_solutions
    runs-on: ubuntu-latest
    container: ghcr.io/${{ needs.get_latest_image_and_solutions.outputs.image }}:latest
    strategy:
      matrix: ${{ fromJSON(needs.get_latest_image_and_solutions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: running ./scripts/print-versions.sh
        run: ./scripts/print-versions.sh
      - name: running ./2021/${{ matrix.day }}/test.sh
        run: ./2021/${{ matrix.day }}/test.sh
