name: Docker Image CI

on:
  push:
    paths:
      - '.github/workflows/docker-image.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: lowercase repository path
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ env.REPO }}:${{ github.sha }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    - name: Push the docker Image
      run: |
        docker push ghcr.io/${{ env.REPO }}:${{ github.sha }}
        docker tag ghcr.io/${{ env.REPO }}:${{ github.sha }} ghcr.io/${{ env.REPO }}:2021
        docker push ghcr.io/${{ env.REPO }}:2021
        docker tag ghcr.io/${{ env.REPO }}:${{ github.sha }} ghcr.io/${{ env.REPO }}:latest
        docker push ghcr.io/${{ env.REPO }}:latest

